M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date Fri 02 Feb 2024 11:32:41 AM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-02T11:32:41-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X118.935Y-171.45
X119.291Y-196.215
M30
